### ISSUE TITLE
miniupnpc & fast_float

### ISSUE THREAD

**Issue by GaryElshaw** [Coeur/transmission#1]
### What is the issue?

Just when you think you're ahead :-) [Miniupnpc 2.2.7](https://github.com/miniupnp/miniupnp/commit/d4d5ec7d48c093b37b2ea5d7171ede21ce9d7ff2) and [fast_float 6.1.1](https://github.com/fastfloat/fast_float)

### Which application of Transmission?

None

**Comment by Coeur** [comment]
Nice. And libdeflate soon soon: https://github.com/ebiggers/libdeflate/pull/352

**Comment by GaryElshaw** [comment]
Libdeflate 1.20 dropped.
