### ISSUE TITLE
Add "Advanced" (was "Memory cache size" #6730) setting to the Preferences

### ISSUE THREAD

**Issue by GaryElshaw** [Coeur/transmission#2]
### What is the issue?

Just my 2c. I think what you're doing is a good idea. Just my personal feeling, the majority of Mac client users won't know about the settings.json file, and most would much rather work within the normal paradigm of Preferences/Settings.

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.1

**Comment by GaryElshaw** [comment]
I'm blocked from the project. I'll work on a standard advanced icon.

**Comment by Coeur** [comment]
I'm considering, one day (not now), adding an "advanced" tab in the visual settings, so that we can edit that settings.json from the UI.

**Comment by GaryElshaw** [comment]
That would be fantastic.

**Comment by GaryElshaw** [comment]
'gearshape.2' is the SF Symbols icon that should be coded for advanced preferences. I haven't resized this because i'm not sure we need this in the imageset, but this is the icon. 

![gearshape2](https://github.com/Coeur/swiftmission/assets/69029666/89dd0d87-5a2d-4465-b28d-8177b8a0e463)

**Comment by GaryElshaw** [comment]
Sorry to see what is happening with Transmission right now, i was hoping the maintainers would open up a write-access spot. I see Charles is very active with Electron instead.

This project is important to me. I have spent an inordinate amount of time, over the last 3 years, daily, pushing for more and better. I cannot 'code', and have had to realise that whatever skills i do have are secondary to Charles' perpetual re-factoring that kills contributions. 

When i first got involved with this project, it was because there were gaps i could see in the client UI's. They still remain. This work, i picked up from Mike, and should have been part of 4 [#4376](https://github.com/transmission/transmission/pull/4376) shoud have been the next state of the client. The reason it wasn't picked up for 4, is Charles.

I thought this was reasonable, as a 'member', without even an ability to tag anything. https://github.com/transmission/transmission/pull/6696

The completely unhinged response, and being banned. 
![image](https://github.com/Coeur/swiftmission/assets/69029666/36ac2944-c13f-4abc-a7ad-ef357832ac95)

**Comment by GaryElshaw** [comment]
For the record, you can't respond if you're blocked and someone is deleting your responses.

I asked to be removed from the authors list. Mike or Mitchell weren't included in my request because Mike and Mitchell are largely absent.
