### ISSUE TITLE
feat: update UI redesign for qt client #4376

### ISSUE THREAD

**Issue by GaryElshaw** [Coeur/transmission#5]
### What is the issue?

@Pentaphon I saw your note, thank you. I am banned from Transmission, and consequently can't communicate, but hope this reaches you.

I still follow the project, daily, because it has been a worthwhile project, to me, since i first started contributing. Unfortunately, over time, Charles and i have hit an impasse on where i think the project needs to be headed, and also an impasse in communication. 

Sadly, i disagree with you, i don't think the project is headed in the right direction right now. Charles is busy with other projects (Electron), but is unwilling, i think to the detriment of the Transmisssion project, to allow write access for @Tearfur. 

I'm also saddened by the state of this pr, and a couple of other pr's of mine, that have tried to, in my mind, unify the client UI's. My hope, over a year ago, and especially after the WebUI redesign, was that all of the clients had some comparable and familiar ui thread, and there would be a seamlessness from client to webui. This pr was always intended to be the first hurdle before changing the GTK ui to make it identical.

I hope someone picks up the work.

All the best. 

### Which application of Transmission?

None

**Comment by Pentaphon** [comment]
@GaryElshaw that is very sad to hear. I was aware of the heated discussion but I had no idea it came to that terrible end with you getting banned. What was the reason for your ban? I can't imagine banning any contributor to a project in need of contributors unless they were doing something malicious.

**Comment by GaryElshaw** [comment]
I asked to be removed from the authors list. https://github.com/Coeur/swiftmission/issues/2#event-12942703911

**Comment by Pentaphon** [comment]
> I asked to be removed from the authors list.

Ah. That is very unfortunate. I do hope Charles has a change of heart but it looks like this is permanent and you have accepted it. I am very sorry it came to this with you and Charles. Thanks for your contributions over the years, Gary. The project won't be the same without an enthusiast like you who can contribute way more than users like me. I really mean that. Take care.

**Comment by Pentaphon** [comment]
@GaryElshaw I believe you are back in action! Just wanted to say I am glad. There was no reason to keep you from contributing to Transmission.

**Comment by GaryElshaw** [comment]
@Pentaphon Sadly, i'm just trying to sort out a conflict i can't get my head around, to get this pr in order before asking if someone else could take it over for me. I'm still banned from the project, which means there are lots of things i can no longer do. I can't comment on this pr, for example, but for some reason pre-existing pr's are still able to be edited.

Guys, are any of you keen to pick up the reins on this pr and push it forward? @Coeur @tearfur Maybe @Schlossgeist? 

The Qt client was the last part of the equation i was hoping to, honestly, take out of theming hell. The icon set is much better than Faenza, but it would be great if someone could take a look at what i was discussing, that i probably [didn't explain well](https://github.com/transmission/transmission/issues/4420). We already harden the icon theme by using Faenza, why not the rest of the interface?

The main bar is done, but it will take someone with code skills to get the progress bars to conform with the other clients. I was hoping to hardwire the Qt client more than others because Qt theming can be such a complete mess, more than GTK. 

Right now, this compiles and runs fine as is, but the conflict exists. If anyone wants to get in touch about anything to do with the pr, and its intent, my email is asituationist@gmail.com

Edit: Conflict is sorted and it should be ready to merge.

**Comment by GaryElshaw** [comment]
> I do hope Charles has a change of heart

I'm pretty confident he used the expression 'hell freezing over', so very unlikely.

**Comment by Coeur** [comment]
> Guys, are any of you keen to pick up the reins on this pr and push it forward? @Coeur

I don't have a Windows at the moment.
That PR is 1400+ lines added? (mostly SVG, but that is still a format that should be code-reviewed ideally)
I'm not a user of the QT app.

So that PR is unfortunately not in _my_ priority list. It would be best tackled by a Windows reviewer.

Even "deleting" unused icons is hard to get approved (my PR 6911 has been opened for two weeks and still has no approval), so adding new icons is a tough battle in this project.

**Comment by Pentaphon** [comment]
> I'm pretty confident he used the expression 'hell freezing over', so very unlikely.

I think Mike Gelfand would be willing to get your PRs to the finish line and he is the main Windows guy on the project. Not sure if we'd even have a Windows port if not for him. I don't think he would care about whatever is going on with you and Charles as long as the project improves.
