### ISSUE TITLE
feat: Monochrome systray icon for GTK and Qt clients

### ISSUE THREAD

**Issue by GaryElshaw** [Coeur/transmission#6]
### What is the issue?

A lot of history behind these. I intitially hard coded these icons and met resistance. I eventually took a more simplistic turn that works. On the linux side of things Ayatana *could* be a prerequisite to solve the issue until GNOME sorts out the future of the systray. Alternatively, i've created systray icons for both clients if someone wants to take a different approach. I'd love someone to pick this up.

https://github.com/transmission/transmission/pull/4973
https://github.com/transmission/transmission/pull/4421

### Which application of Transmission?

GTK+ and Qt app on Linux, BSD, etc.

### Which version of Transmission?

4.1

**Comment by Coeur** [comment]
I'm really just trying to deal with the macOS app maintenance. GTK and Qt UI would probably need different reviewers than me. That "Ayatana" dependency is really out of my skills unfortunately.
