### ISSUE TITLE
Transmission 4.0.7

### ISSUE THREAD

**Issue by GaryElshaw** [Coeur/transmission#9]
### What is the issue?

@Coeur Can you please make sure they include [#6753](https://github.com/transmission/transmission/pull/6753)

### Which application of Transmission?

All

### Which version of Transmission?

4.0.7

**Comment by Pentaphon** [comment]
Made sure to add it here: https://github.com/transmission/transmission/issues/7094

**Comment by GaryElshaw** [comment]
@Coeur I can barely contain my anger how this project has willingly been ignored by the maintainers when the client is banned. Kudos to you for [providing a path](https://github.com/transmission/transmission/issues/7094#issuecomment-2355127522). I appreciate it.

The alternative is just to release 4.1 as-is (without beta), and apply the fixes as subsequent releases. @tearfur

Otherwise, i'm sticking with forking the project. Charles isn't just spending his work weekdays on [Electron](https://github.com/electron/electron/pulls), it includes his weekends. We can debate definitions of 'abandonment', but one of mine is every maintainer not scrambling when the client is banned. When it's been acknowledged, for weeks.
